include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    unnecessary_parenthesis: true
    always_declare_return_types: true
