name: enmeshed
repository: https://github.com/nmshd/cns-app

packages:
  - "apps/*"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "dart format . --set-exit-if-changed -l 150"
    description: Run `dart format .` in all packages

  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test --flutter -- "flutter test" && melos exec --dir-exists=test --no-flutter -- "dart test"
    description: Run `flutter test` in all packages

  # https://github.com/dart-code-checker/dart-code-metrics/issues/313
  # flutter analyze cannot use the dcm plugin
  metrics:
    run: melos exec -c 1 -- flutter pub run dart_code_metrics:metrics analyze lib
    description: |
      Run `dart_code_metrics` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.
