name: enmeshed
repository: https://github.com/nmshd/app

packages:
  - "apps/*"
  - "packages/**"

ide:
  intellij:
    enabled: false

command:
  format:
    lineLength: 150
    setExitIfChanged: true

scripts:
  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test --flutter -- "flutter test" && melos exec --dir-exists=test --no-flutter -- "dart test"
    description: Run `flutter test` in all packages

  integration_test:
    run: melos exec --dir-exists=integration_test --flutter -- "flutter test --dart-define-from-file=../../config.json integration_test/suite_test.dart"
    description: Run `integration tests` in all packages that have the folder `integration_test``

  outdated:
    run: melos exec -c 1 --no-flutter -- "dart pub outdated" && melos exec -c 1 --flutter -- "flutter pub outdated"
    description: Run `dart pub outdated` in all packages

  check_translations:
    run: melos exec --dir-exists=lib/l10n --flutter -- "dart run translations_cleaner list-unused-terms --abort-on-unused"
    description: Check translations in all packages

  clean_translations:
    run: melos exec --dir-exists=lib/l10n --flutter -- "dart run translations_cleaner clean-translations && npx prettier -w lib/l10n/*.arb --parser json"
    description: Check translations in all packages
