include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unnecessary_null_check_pattern: false

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    unnecessary_parenthesis: true
    always_declare_return_types: true
    use_null_aware_elements: true
    constant_identifier_names: false

formatter:
  page_width: 150
