/// Flutter icons EnmeshedIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EnmeshedIcons
///      fonts:
///       - asset: fonts/EnmeshedIcons.ttf
///
///
///

// ignore_for_file: unused_field, use_late_for_private_fields_and_variables, dangling_library_doc_comments

import 'package:flutter/widgets.dart';

class EnmeshedIcons {
  EnmeshedIcons._();

  static const _kFontFam = 'EnmeshedIcons';
  static const String? _kFontPkg = null;

  static const IconData deviceAdd = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData requestCertificate = IconData(0xe801, fontFamily: _kFontFam);
}
