services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:6.45.0@sha256:15cc6154b88aac76fb68fb603cc1931443086028055c7121354620f0acde0a7c
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:6.45.0@sha256:419549ae8dc150836becf077b191ce8c39a6904a5480ff16320f5790ecdfb351
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:6.45.0@sha256:6c79c9a4e5c6a9308929a1ed4ce732178c015fc9bc735fe0cd6ceffde7e12a9e
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    image: ghcr.io/nmshd/backbone-admin-ui:6.45.0@sha256:f6b2543a0157b533686d8c2a829f63d59b70452d0e8bbf76d9d7db97555e8fc5
    container_name: admin-ui
    hostname: admin-ui
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      consumer-api:
        condition: service_healthy
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator-test
    image: ghcr.io/nmshd/backbone-database-migrator:6.45.0@sha256:d55f969b820cad0fce9719d4cf5a79bf1f3c7d3e23680c16e8584540bd8ef46e
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:6efd0df010dc3cb40d5e33e3ef84acecc5e73161bd3df06029ee8698e5e12c60
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:0a47e12e3693483cef5c71f35468b91d751611f172d2f97414e9c69113b106d9
    pull_policy: always
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"
    ports:
      - "10000:10000"

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.1.0-alpine@sha256:8a73e9185f8420247c5b3c19231df18dfac28a8d5706203e13b291934044966d
    ports:
      - "5672:5672"

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:6.45.0@sha256:a77506be1d6f8cc3aa3df42e6408d5e7fd03244456b3c631217e45d0241a783d
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

networks:
  default:
    name: backbone

configs:
  Config:
    file: appsettings.override.json
