name: enmeshed_ui_kit
description: A Dart package exposing a set of widgets and utilities to build Enmeshed Apps.
version: 1.0.0

environment:
  sdk: "^3.8.1"
  flutter: ">=3.32.8"

dependencies:
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^16.0.0
  logger: ^2.6.1
  path: any
  styled_text: ^8.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
