name: enmeshed_ui_kit
description: A Dart package exposing a set of widgets and utilities to build Enmeshed Apps.
version: 1.0.0

environment:
  sdk: "^3.8.1"
  flutter: ">=3.32.5"

dependencies:
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  go_router: ">=15.2.4"
  path: any
  styled_text: ^8.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
