name: Build Connector UI

on:
  push:
    branches-ignore: [main, release/**]

jobs:
  build-connector-ui-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/apps/connector_ui
      - run: npx appdmg ./installers/dmg_creator/config.json ./connector_ui.dmg
        working-directory: ${{ github.workspace }}/apps/connector_ui
      - uses: actions/upload-artifact@v3
        with:
          name: mac app
          path: ./apps/connector_ui/connector_ui.dmg
