name: Build Connector UI

on:
  push:
    branches: [main, release/**]
    paths:
      - apps/connector_ui/**

jobs:
  build-connector-ui-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/apps/connector_ui
      - run: npx appdmg ./installers/dmg_creator/config.json ./connector_ui.dmg
        working-directory: ${{ github.workspace }}/apps/connector_ui
      - uses: actions/upload-artifact@v4
        with:
          name: mac app
          path: ./apps/connector_ui/connector_ui.dmg

  build-connector-ui-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: flutter build windows --release
        working-directory: ${{ github.workspace }}/apps/connector_ui
      - uses: actions/upload-artifact@v4
        with:
          name: windows app
          path: ./apps/connector_ui/build/windows/x64/runner/Release
