on:
  push:
name: enmeshed_bridge integration tests
jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [playstore]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: "2.8.1"
          channel: "stable"
      - run: flutter --version

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 9
          script: flutter test --dart-define-from-file=./config.json packages/enmeshed_runtime_bridge/integration_test/suite_test.dart
