on:
  push:
name: enmeshed_bridge integration tests
jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [playstore]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: "2.8.1"
          channel: "stable"
      - run: flutter --version
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: |
          cd ./packages/enmeshed_runtime_bridge
          flutter pub get

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # Run integration test
      - name: Start emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          arch: x86_64
          profile: Nexus 9
          script: cd packages/enmeshed_runtime_bridge && flutter test integration_test/suite_test.dart
